# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a87af1d45cd3f401ee18f9eb6073a710bf0e03f4

{
  "title": "8-е объявление первого пользователя",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/8/
Content-Type: application/json
Authorization: Token a87af1d45cd3f401ee18f9eb6073a710bf0e03f4

{
  "status": "CLOSED"
}

###

# фильтрация по создателю и статусу
GET {{baseUrl}}/advertisements/?creator=1&status=OPEN
Content-Type: application/json


###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-02-15
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 6ef25d7078ccdedfbef373b6ba9079ff9a9547ce

{
  "title": "Новая тумбочка Hoff",
  "description": "Срочно продам"
}

###

# попытка поменять объявление другим пользователем
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 6ef25d7078ccdedfbef373b6ba9079ff9a9547ce

{
  "status": "CLOSED"
}

###

# запрос конкретного объявления

GET {{baseUrl}}/advertisements/3/
Content-Type: application/json
#Authorization: Token 6ef25d7078ccdedfbef373b6ba9079ff9a9547ce

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

